name: vmb_portfolio
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.7.0
  cupertino_icons: ^1.0.8
  bordered_text: ^2.0.0
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2785.1
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.1
  flutter_linkify: ^6.0.0
  image: ^4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pictures/catcher/
    - assets/pictures/icons/
    - assets/pictures/projects/
    - assets/pictures/projects/portfolio/
    - assets/pictures/projects/robuzzle/
    - assets/pictures/projects/spacewars/
    - assets/pictures/projects/snake/
